# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'REV00.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QApplication
from PyQt5.QtCore import Qt
import socket
from Writeviamac import Ui_Writeviamac
import sys
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

class Ui_SearchviaMAC(object):
    def setupUi(self, SearchviaMAC):
        SearchviaMAC.setObjectName("SearchviaMAC")
        SearchviaMAC.resize(452, 269)
        SearchviaMAC.setStyleSheet("background-color: rgb(225, 225, 235);")
        self.centralwidget = QtWidgets.QWidget(SearchviaMAC)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mac1in = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mac1in.sizePolicy().hasHeightForWidth())
        self.mac1in.setSizePolicy(sizePolicy)
        self.mac1in.setMaximumSize(QtCore.QSize(35, 20))
        self.mac1in.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mac1in.setAlignment(QtCore.Qt.AlignCenter)
        self.mac1in.setObjectName("mac1in")
        self.horizontalLayout.addWidget(self.mac1in)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.mac2in = QtWidgets.QLineEdit(self.centralwidget)
        self.mac2in.setMaximumSize(QtCore.QSize(35, 20))
        self.mac2in.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mac2in.setAlignment(QtCore.Qt.AlignCenter)
        self.mac2in.setObjectName("mac2in")
        self.horizontalLayout.addWidget(self.mac2in)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.mac3in = QtWidgets.QLineEdit(self.centralwidget)
        self.mac3in.setMaximumSize(QtCore.QSize(35, 20))
        self.mac3in.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mac3in.setAlignment(QtCore.Qt.AlignCenter)
        self.mac3in.setObjectName("mac3in")
        self.horizontalLayout.addWidget(self.mac3in)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.mac4in = QtWidgets.QLineEdit(self.centralwidget)
        self.mac4in.setMaximumSize(QtCore.QSize(35, 20))
        self.mac4in.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mac4in.setAlignment(QtCore.Qt.AlignCenter)
        self.mac4in.setObjectName("mac4in")
        self.horizontalLayout.addWidget(self.mac4in)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.mac5in = QtWidgets.QLineEdit(self.centralwidget)
        self.mac5in.setMaximumSize(QtCore.QSize(35, 20))
        self.mac5in.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mac5in.setAlignment(QtCore.Qt.AlignCenter)
        self.mac5in.setObjectName("mac5in")
        self.horizontalLayout.addWidget(self.mac5in)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.mac6in = QtWidgets.QLineEdit(self.centralwidget)
        self.mac6in.setMaximumSize(QtCore.QSize(35, 20))
        self.mac6in.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mac6in.setCursorPosition(0)
        self.mac6in.setAlignment(QtCore.Qt.AlignCenter)
        self.mac6in.setObjectName("mac6in")
        self.horizontalLayout.addWidget(self.mac6in)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 2, 1, 1)
        self.sistemidind = QtWidgets.QLabel(self.centralwidget)
        self.sistemidind.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.sistemidind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sistemidind.setIndent(2)
        self.sistemidind.setObjectName("sistemidind")
        self.gridLayout.addWidget(self.sistemidind, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.slotidind = QtWidgets.QLabel(self.centralwidget)
        self.slotidind.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.slotidind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slotidind.setIndent(2)
        self.slotidind.setObjectName("slotidind")
        self.gridLayout.addWidget(self.slotidind, 1, 4, 1, 1)
        self.rackidind = QtWidgets.QLabel(self.centralwidget)
        self.rackidind.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.rackidind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rackidind.setIndent(2)
        self.rackidind.setObjectName("rackidind")
        self.gridLayout.addWidget(self.rackidind, 1, 3, 1, 1)
        self.ipind = QtWidgets.QLabel(self.centralwidget)
        self.ipind.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(0, 0, 0);")
        self.ipind.setIndent(2)
        self.ipind.setObjectName("ipind")
        self.gridLayout.addWidget(self.ipind, 2, 2, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 1, 1, 1)
        self.subnetind = QtWidgets.QLabel(self.centralwidget)
        self.subnetind.setStyleSheet("background-color: rgb(212, 208, 200);\n"
"border-color: rgb(212, 208, 200);")
        self.subnetind.setIndent(2)
        self.subnetind.setObjectName("subnetind")
        self.gridLayout.addWidget(self.subnetind, 3, 2, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 6, 1, 1)

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setEnabled(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 1, 1, 1)
        self.gatewayind = QtWidgets.QLineEdit(self.centralwidget)
        self.gatewayind.setEnabled(True)
        self.gatewayind.setStyleSheet("background-color: rgb(212, 208, 200);\n"
                                      "border-color: rgb(0, 0, 0);")
        self.gatewayind.setObjectName("gatewayind")
        self.gridLayout.addWidget(self.gatewayind, 4, 2, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)

        self.changepb = QtWidgets.QPushButton(self.centralwidget)
        self.changepb.setEnabled(False)
        self.changepb.setObjectName("changepb")
        self.gridLayout.addWidget(self.changepb, 2, 5, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.searchpb = QtWidgets.QPushButton(self.centralwidget)
        self.searchpb.setObjectName("searchpb")
        self.horizontalLayout_2.addWidget(self.searchpb)
        self.cancelpb = QtWidgets.QPushButton(self.centralwidget)
        self.cancelpb.setObjectName("cancelpb")
        self.horizontalLayout_2.addWidget(self.cancelpb)
        self.applypb = QtWidgets.QPushButton(self.centralwidget)
        self.applypb.setEnabled(False)
        self.applypb.setObjectName("applypb")
        self.horizontalLayout_2.addWidget(self.applypb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        SearchviaMAC.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SearchviaMAC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 26))
        self.menubar.setObjectName("menubar")
        SearchviaMAC.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SearchviaMAC)
        self.statusbar.setObjectName("statusbar")
        SearchviaMAC.setStatusBar(self.statusbar)

        self.mac1in.setMaxLength(2)
        self.mac2in.setMaxLength(2)
        self.mac3in.setMaxLength(2)
        self.mac4in.setMaxLength(2)
        self.mac5in.setMaxLength(2)
        self.mac6in.setMaxLength(2)
        self.mac4in.setFocus()

        self.mac1in.textChanged[str].connect(self.jump2)
        self.mac2in.textChanged[str].connect(self.jump3)
        self.mac3in.textChanged[str].connect(self.jump4)
        self.mac4in.textChanged[str].connect(self.jump5)
        self.mac5in.textChanged[str].connect(self.jump6)
        self.mac6in.textChanged[str].connect(self.focusSearchButton)

        regexp = QtCore.QRegExp(r'[0123456789abcdefABCDEF][0123456789abcdefABCDEF]')
        validator = QtGui.QRegExpValidator(regexp)
        self.mac1in.setValidator(validator)
        self.mac2in.setValidator(validator)
        self.mac3in.setValidator(validator)
        self.mac4in.setValidator(validator)
        self.mac5in.setValidator(validator)
        self.mac6in.setValidator(validator)

        self.searchpb.clicked.connect(self.searchclicked)
        self.cancelpb.clicked.connect(self.close)
        self.changepb.clicked.connect(self.openwriteviamac)

        self.retranslateUi(SearchviaMAC)
        QtCore.QMetaObject.connectSlotsByName(SearchviaMAC)

    def retranslateUi(self, SearchviaMAC):
        _translate = QtCore.QCoreApplication.translate
        SearchviaMAC.setWindowTitle(_translate("SearchviaMAC", "Search via MAC"))
        self.label.setText(_translate("SearchviaMAC", "MAC Address"))
        self.mac1in.setText(_translate("SearchviaMAC", "00"))
        self.label_7.setText(_translate("SearchviaMAC", " - "))
        self.mac2in.setText(_translate("SearchviaMAC", "e0"))
        self.label_6.setText(_translate("SearchviaMAC", " - "))
        self.mac3in.setText(_translate("SearchviaMAC", "a1"))
        self.label_3.setText(_translate("SearchviaMAC", " - "))
        self.label_5.setText(_translate("SearchviaMAC", " - "))
        self.label_4.setText(_translate("SearchviaMAC", " - "))
        self.sistemidind.setText(_translate("SearchviaMAC", "0"))
        self.label_2.setText(_translate("SearchviaMAC", "SRS"))
        self.slotidind.setText(_translate("SearchviaMAC", "0"))
        self.rackidind.setText(_translate("SearchviaMAC", "0"))
        self.ipind.setText(_translate("SearchviaMAC", "0 .0 .0 .0"))
        self.label_9.setText(_translate("SearchviaMAC", "Subnet Mask"))
        self.subnetind.setText(_translate("SearchviaMAC", "0 .0 .0 .0"))
        self.label_8.setText(_translate("SearchviaMAC", "IP Address"))
        self.label_16.setText(_translate("SearchviaMAC", "  Setting"))
        self.changepb.setText(_translate("SearchviaMAC", "Change"))
        self.label_10.setText(_translate("SearchviaMAC", "Gateway"))
        self.gatewayind.setText(_translate("SearchviaMAC", "0 .0 .0 .0"))
        self.searchpb.setText(_translate("SearchviaMAC", "Search"))
        self.cancelpb.setText(_translate("SearchviaMAC", "Cancel"))
        self.applypb.setText(_translate("SearchviaMAC", "Apply"))

    def openwriteviamac(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Writeviamac()
        self.ui.mac1 = self.mac1in.text()
        self.ui.mac2 = self.mac2in.text()
        self.ui.mac3 = self.mac3in.text()
        self.ui.mac4 = self.mac4in.text()
        self.ui.mac5 = self.mac5in.text()
        self.ui.mac6 = self.mac6in.text()
        self.ui.sisId = self.sistemidind.text()
        self.ui.rackId = self.rackidind.text()
        self.ui.slotId = self.slotidind.text()
        self.ui.ip = self.ipind.text()
        self.ui.subnet = self.subnetind.text()
        self.ui.gateway = self.gatewayind.text()

        self.ui.setupUi(self.window)
        self.window.show()

    def jump2(self):
        if len(self.mac1in.text()) == 2:
            self.mac2in.setFocus()
            self.mac2in.selectAll()

    def jump3(self):
        if len(self.mac2in.text()) == 2:
            self.mac3in.setFocus()
            self.mac3in.selectAll()

    def jump4(self):
        if len(self.mac3in.text()) == 2:
            self.mac4in.setFocus()
            self.mac4in.selectAll()

    def jump5(self):
        if len(self.mac4in.text()) == 2:
            self.mac5in.setFocus()
            self.mac5in.selectAll()

    def jump6(self):
        if len(self.mac5in.text()) == 2:
            self.mac6in.setFocus()
            self.mac6in.selectAll()

    def focusSearchButton(self):
        if len(self.mac6in.text()) == 2:
            self.searchpb.setAutoDefault(True)

    def close(self):
        self.close()

    def warningmessage(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Warning)
        msg.setText("Enter a Valid MAC Address")
        msg.setWindowTitle("Search via MAC")
        msg.setStandardButtons(QMessageBox.Ok)
        retval = msg.exec_()

    def informationmessage(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("No response within waiting time")
        msg.setWindowTitle("Search via MAC")
        msg.setStandardButtons(QMessageBox.Ok)
        retval = msg.exec_()

    def searchclicked(self):
        try:
            mc1 = int(self.mac1in.text(), 16)
            mc2 = int(self.mac2in.text(), 16)
            mc3 = int(self.mac3in.text(), 16)
            mc4 = int(self.mac4in.text(), 16)
            mc5 = int(self.mac5in.text(), 16)
            mc6 = int(self.mac6in.text(), 16)
            self.updatedata(mc1, mc2, mc3, mc4, mc5, mc6)
        except :
            self.warningmessage()

    def updatedata(self, mc1, mc2, mc3, mc4, mc5, mc6):
        QApplication.setOverrideCursor(Qt.WaitCursor)

        interfaces = socket.getaddrinfo(host=socket.gethostname(), port=None, family=socket.AF_INET)
        allips = [ip[-1][0] for ip in interfaces]

        hex_list = [0x00, 0x02, 0xe7, 0x5c, 0x00, 0x02, 0xe7, 0x5c, 0x00, 0x02, 0xe7, 0x5c, 0x00, 0x02, 0xe7, 0x5c,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x8c, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, mc1, mc2, mc3, mc4, mc5, mc6, 0x08, 0xf7]
        data = 0
        for ip in allips:
            print(f'sending on {ip}')
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
            s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
            s.bind((ip, 0))
            s.sendto(bytes(hex_list), ("255.255.255.255", 8000))
            s.settimeout(1.0)
            try:
                data = str(s.recv(1024).hex())
                break
            except socket.timeout:
                print("Didn't receive data with " + ip + "! [Timeout]")
            finally:
                s.close()

        QApplication.restoreOverrideCursor()
        if len(data) <= 328:
            ld = len(data)
            sistemid = str(int(data[ld-72:ld-72+4], 16))
            riddata = str(data[ld-68:ld-68+4])
            rackid = (int(riddata[:2], 16)*4) + (int(riddata[2:], 16)//64)
            ip = str(int(data[ld-48:ld-48+2], 16)) + "." + str(int(data[ld-46:ld-46+2], 16)) + "." \
                 + str(int(data[ld-44:ld-44+2], 16)) + "." + str(int(data[ld-42:ld-42+2], 16))
            subnet = str(int(data[ld-40:ld-40+2], 16)) + "." + str(int(data[ld-38:ld-38+2], 16)) + "." \
                 + str(int(data[ld-36:ld-36+2], 16)) + "." + str(int(data[ld-34:ld-34+2], 16))
            gateway = str(int(data[ld-32:ld-32+2], 16)) + "." + str(int(data[ld-30:ld-30+2], 16)) + "." \
                 + str(int(data[ld-28:ld-28+2], 16)) + "." + str(int(data[ld-26:ld-26+2], 16))
            self.sistemidind.setText(sistemid)
            self.rackidind.setText(str(rackid))
            self.ipind.setText(ip)
            self.subnetind.setText(subnet)
            self.gatewayind.setText(gateway)
            self.changepb.setDisabled(False)
        elif len(data) <= 496:
            ld = len(data)
            sistemid = str(int(data[ld-72:ld-72+4], 16))
            ip = str(int(data[ld-40:ld-40+2], 16)) + "." + str(int(data[ld-38:ld-38+2], 16)) + "." \
                 + str(int(data[ld-36:ld-36+2], 16)) + "." + str(int(data[ld-34:ld-34+2], 16))
            subnet = str(int(data[ld-23:ld-23+2], 16)) + "." + str(int(data[ld-21:ld-21+2], 16)) + "." \
                 + str(int(data[ld-19:ld-19+2], 16)) + "." + str(int(data[ld-17:ld-17+2], 16))
            gateway = str(int(data[ld-8:ld-8+2], 16)) + "." + str(int(data[ld-6:ld-6+2], 16)) + "." \
                 + str(int(data[ld-4:ld-4+2], 16)) + "." + str(int(data[ld-2:ld], 16))
            self.sistemidind.setText(sistemid)
            self.ipind.setText(ip)
            self.subnetind.setText(subnet)
            self.gatewayind.setText(gateway)
            self.changepb.setDisabled(False)
        else:
            self.informationmessage()
            self.changepb.setDisabled(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchviaMAC = QtWidgets.QMainWindow()
    ui = Ui_SearchviaMAC()
    ui.setupUi(SearchviaMAC)
    SearchviaMAC.show()
    sys.exit(app.exec_())
